# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/mirrors-prettier/mirrors-prettier
    rev: 'v3.9.6' # Use the sha / tag you want to point at
    hooks:
      - id: prettier
