name: Conan Setup
description: Sets up the Conan Package Manager
author: 'Andrew Marshall <planetmarshalluk@gmail.com>'
inputs:
  config:
    description: 'Install a configuration from a file or url'
    required: false
  cache-key:
    description: 'Explicitly specify a cache key to use'
    required: false
  lockfile:
    description: |
      Path to a conan lockfile to use as part of the cache key. The default is the empty string which will use
      'conan.lock' if it exists in the workspace root, otherwise no lockfile will be hashed. It is an error to specify
      a lockfile which does not exist.
    required: false
    default: ''
  append-timestamp:
    description: 'Append a timestamp to the cache key to force an overwrite of the cache'
    required: false
    default: false
  remotes:
    description: 'A list of remotes to authorize. Use environment variables to supply credentials'
    required: false
  save:
    description: 'Whether to save the package cache'
    required: false
    default: true
runs:
  using: node20
  main: dist/main/index.js
  post: dist/save/index.js
