name: Conan Setup
description: Sets up the Conan Package Manager
author: Andrew Marshall
inputs:
  config:
    description: 'install a configuration from a file or url'
    required: false
  cache-key:
    description: 'explicitly specify a cache key to use'
    required: false
  append-timestamp:
    description: 'append a timestamp to the cache key to always force an update'
    required: false
    default: 'true'
runs:
  using: node20
  main: dist/main/index.js
  post: dist/save/index.js
