name: Conan Setup
description: Sets up the Conan Package Manager
author: 'Andrew Marshall <planetmarshalluk@gmail.com>'
inputs:
  append-timestamp:
    description: 'Append a timestamp to the cache key to force an overwrite of the cache'
    required: false
    default: 'false'
  cache:
    description: 'Enable the github cache'
    required: false
    default: 'true'
  cache-key:
    description: 'Explicitly specify a cache key to use'
    required: false
  config:
    description: 'Install a configuration from a file or url'
    required: false
  host-profiles:
    description: A list of host profiles to use when generating the cache key
    required: false
    default: ''
  lockfile:
    description: |
      Path to a conan lockfile to use as part of the cache key. The default is the empty string which will use
      'conan.lock' if it exists in the workspace root, otherwise no lockfile will be hashed. It is an error to specify
      a lockfile which does not exist.
    required: false
    default: ''
  remotes:
    description: 'A list of remotes to authorize. Use environment variables to supply credentials'
    required: false
  save:
    description: 'Whether to save the package cache'
    required: false
    default: 'true'
  version:
    description: |
      The conan version to install. 'latest' for the latest version, or 'auto' to use an existing version or
      the latest if no version exists.
    required: false
    default: 'auto'
branding:
  icon: 'package'
  color: 'blue'

runs:
  using: node20
  main: dist/main/index.js
  post: dist/save/index.js
