name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Static Analysis and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run ci-test

      - name: Check package is up to date
        run: |
          npm run bundle
          OUTPUT=$(git diff -- dist | wc --chars)
          if [[ "${OUTPUT}" -ne "0" ]]; then
            echo "::error::package files are not up to date"
            exit 1
          fi

  action-tests:
    name: '${{ matrix.name }} (${{ matrix.runner }})'
    strategy:
      matrix:
        include:
          - name: default
            runner: ubuntu-latest
            config: ''
            append-timestamp: true

          - name: default
            runner: macos-latest
            config: ''
            append-timestamp: false

          - name: default
            runner: windows-latest
            config: ''
            append-timestamp: false

          - name: install config
            runner: ubuntu-latest
            config: '.github/workflows/config'
            append-timestamp: false
            test: true

          - name: install config
            runner: macos-latest
            config: '.github/workflows/config'
            append-timestamp: false
            test: true

          - name: install config
            runner: windows-latest
            config: '.github/workflows/config'
            append-timestamp: false
            test: true

          - name: cache key with timestamp
            runner: ubuntu-latest
            append-timestamp: false

    runs-on: ${{ matrix.runner }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: '.github/requirements.txt'

      - name: Install conan
        run: |
          pip install \
            conan \
            pytest

      - name: Run local action
        uses: ./
        with:
          config: ${{ matrix.config }}
          append-timestamp: ${{ matrix.append-timestamp }}

      - name: Run tests
        if: matrix.test != ''
        run: |
          pytest integration_tests

      - name: Install packages
        run: |
          conan install .github --build missing
