name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Static Analysis and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run ci-test

      - name: Check package is up to date
        run: |
          npm run bundle
          OUTPUT=$(git diff -- dist | wc --chars)
          if [[ "${OUTPUT}" -ne "0" ]]; then
            echo "::error::package files are not up to date"
          fi
  action-tests:
    strategy:
      matrix:
        config: ['', '.github/workflows/config']
        cache-key: ['', 'linux-key']
        append-timestamp: [false, true]
        remotes: ['']
        include:
          - config: '.github/workflows/config'
            test: test.py

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: '.github/requirements.txt'

      - name: Install conan
        run: |
          pip install \
            conan \
            pytest

      - name: Run local action
        uses: ./
        with:
          cache-key: ${{ matrix.cache-key }}
          append-timestamp: ${{ matrix.append-timestamp }}
          config: ${{ matrix.config }}
          remotes: ${{ matrix.remotes }}

      - name: Install packages
        run: |
          conan install .github --build missing

      - name: Run tests
        if: matrix.test != ''
        run: |
          pytest tests
